# Generated by Django 5.2.8 on 2025-12-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uk_size', models.PositiveSmallIntegerField(choices=[(4, 'UK 4'), (6, 'UK 6'), (8, 'UK 8'), (10, 'UK 10'), (12, 'UK 12'), (14, 'UK 14'), (16, 'UK 16'), (18, 'UK 18'), (20, 'UK 20')], unique=True)),
                ('bust', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waist', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hips', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
