# Generated by Django 5.2.8 on 2025-12-24 19:17

from django.db import migrations

def populate_sizes(apps, schema_editor):
    Size = apps.get_model("size", "Size")
    
    sizes = [
        (4, 31, 23, 33),
        (6, 32, 24, 34),
        (8, 33, 25, 35),
        (10, 34, 26, 36),
        (12, 36, 28, 38),
        (14, 38, 30, 40),
        (16, 40, 32, 42),
        (18, 42, 34, 44),
        (20, 44, 36, 46),
    ]
    
    for uk, bust, waist, hips in sizes:
        Size.objects.create(
            uk_size=uk,
            bust=bust,
            waist=waist,
            hips=hips
        )

class Migration(migrations.Migration):

    dependencies = [
        ('size', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_sizes),
    ]
