# Generated by Django 5.2.8 on 2025-12-25 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('size', '0002_populate_uk_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='size.size'),
            preserve_default=False,
        ),
    ]
