# Generated by Django 5.2.8 on 2025-12-26 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_initial'),
        ('inventory', '0002_remove_inventoryitem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='order',
        ),
        migrations.AddField(
            model_name='image',
            name='inventory_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.inventoryitem'),
            preserve_default=False,
        ),
    ]
